refresh_interval_secs: 15 

hosts:
  "Google": 
    layer     : "cloud" 
    min_request_interval: 0 # Nuvem geralmente aguenta tudo, então 0 ou baixo
    faas_urls : 
      - "http://35.198.21.81:30080/function/crowdcount-yolo"

  "Desktop":
    priority           : "low" 
    layer              : "fog"                           
    min_request_interval: 5 # Novo parametro: espera 5s antes de reenviar carga para cá
    faas_urls          :
      - "http://10.81.24.151:31112/function/crowdcount-yolo" 
    prometheus_api_url : "http://10.81.24.151:9000/api/v1/query" 
    max_cpu_use        : 30 
    max_ram_use        : 90 
    
  "TVBox":
    priority           : "high"
    layer              : "edge"
    min_request_interval: 10 # TVBox é mais fraca, intervalor maior (10s)
    faas_urls          :
      - "http://10.81.24.31:8080/function/crowdcount-yolo"
    prometheus_api_url : "http://10.81.24.31:9000/api/v1/query"
    max_cpu_use        : 80
    max_ram_use        : 90
